global:
  resolve_timeout: 5m
  smtp_smarthost: ${SMTP_SMARTHOST}
  smtp_from: ${SMTP_FROM}
  smtp_auth_username: ${SMTP_USERNAME}
  smtp_auth_password: ${SMTP_PASSWORD}

# Default route, with severity subroutes to Slack (optional).
route:
  receiver: 'default'
  group_by: ['alertname', 'job', 'instance']
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - receiver: 'slack-critical'
      matchers:
        - severity = "critical"
      continue: true
    - receiver: 'email-critical'
      matchers:
        - severity = "critical"
    - receiver: 'slack-warning'
      matchers:
        - severity = "warning"
      continue: true
    - receiver: 'email-warning'
      matchers:
        - severity = "warning"

receivers:
  - name: 'default'
  - name: 'slack-warning'
    slack_configs:
      - api_url: ${SLACK_API_URL}
        channel: ${SLACK_CHANNEL_WARN}
        send_resolved: true
        title: '{{ template "medflux.title" . }}'
        text: '{{ template "medflux.text" . }}'
  - name: 'slack-critical'
    slack_configs:
      - api_url: ${SLACK_API_URL}
        channel: ${SLACK_CHANNEL_CRIT}
        send_resolved: true
        title: '{{ template "medflux.title" . }}'
        text: '{{ template "medflux.text" . }}'
  - name: 'email-warning'
    email_configs:
      - to: ${EMAIL_TO_WARN}
        send_resolved: true
  - name: 'email-critical'
    email_configs:
      - to: ${EMAIL_TO_CRIT}
        send_resolved: true

templates:
  - /etc/alertmanager/templates.tmpl
