global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'bruecke.zum.erfolg@gmail.com'
  smtp_auth_username: 'bruecke.zum.erfolg@gmail.com'
  smtp_auth_password: 'wifolukxztqjnoeo'
  smtp_require_tls: true

route:
  # Email temporarily disabled: route to blackhole receiver
  receiver: 'blackhole'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: 'blackhole'
  - name: 'email'
    email_configs:
      - to: 'bruecke.zum.erfolg@gmail.com'
